name: Build Dylib on macOS

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-macos:
    
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin     # Intel Macs
          - aarch64-apple-darwin    # Apple Silicon
  
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Cross Dependencies
        run: |
          cargo install cross

      - name: Build Dylib
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename .dylib to target-specific name
        run: |
          mv target/${{ matrix.target }}/release/lib*.dylib target/${{ matrix.target }}/release/chlaty-lib-superembed-${{ matrix.target }}.dylib


      - name: Upload .dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-chlaty-lib-superembed-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/chlaty-lib-superembed-${{ matrix.target }}.dylib
